### ISSUE TITLE
Dataset page - under development catch all

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#142]
There is many small things here and there issing on the dataset page. This issue is intended to catch all those small issues as we spot them

* [ ] doi should resolve to a url
* [ ] doi should indicate if it is linking to an external url or the page itself.
* [ ] tabs should be async using ui router https://github.com/gbif/portal16/issues/137
* [ ] there is missing data for collections, curatorial units and more. go through all possible data and ensure that it is included somewhere or consciously excluded
* [ ] metrics tab is largely unimplemented https://github.com/gbif/portal16/issues/138
* [ ] taxonomy tab is still in its early stage. how to navigate? async? show species info inline? and much more. See also https://github.com/gbif/portal16/issues/139
* [ ] show geographical coverage on map
* [ ] when no geographical coverage provided then show card telling that (if no occurrences either)
* [ ] origin tab is missing info and styling.
* [ ] add sync, modified date in corner as on occurrence pages
* [ ] download link is leading no where (we haven't a download page yet)
* [ ] hover effects on metrics on landing page so that it is known that they are links

**Comment by dnoesgaard** [comment]
I think the list of vernacular names could be styled to make it more accessible. Something like putting language in caps in front and keeping everything in neat columns. I tried to illustrate my idea here

![screen shot 2016-11-11 at 14 05 51](https://cloud.githubusercontent.com/assets/21358085/20215968/24425870-a818-11e6-81a8-0d510ae9a268.png)

(_if_ using background color on language it should probably be done nicer than I did ;))

Anyway, just an idea...

**Comment by MortenHofft** [comment]
@dnoesgaard is this related to dataset or species pages?

**Comment by dnoesgaard** [comment]
My bad, this is of course related to species pages, not to datasets. Sorry!

**Comment by kbraak** [comment]
@MortenHofft from the publisher's perspective, it is very important the existing functionality of the dataset page be retained. Existing functionality that has gone missing and represents a regression and release blocker IMHO include: 
* Contributor's ORCID missing - https://github.com/gbif/portal16/issues/318
* Interpretation issues and other data stats missing from dataset (metrics) page - https://github.com/gbif/portal16/issues/300 & https://github.com/gbif/portal16/issues/138
* The metrics tab on dataset page is not shown for checklists - https://github.com/gbif/portal16/issues/331
* Dataset page: Links to "occurrences" and "species" are not working - https://github.com/gbif/portal16/issues/312
* Alternate identifier "Source webpage" mislabelled 'URL" - https://github.com/gbif/portal16/issues/303
* Technically served by link doesn't work - https://github.com/gbif/portal16/issues/302
* Confusing and potentially wrong dates shown on dataset page - https://github.com/gbif/portal16/issues/299
* Metadata (EML) link gives 404 - https://github.com/gbif/portal16/issues/291
* Display general Distribution for dataset - https://github.com/gbif/portal16/issues/320
* LInk to dataset homepage? - https://github.com/gbif/portal16/issues/219
* Chapter title is covered by tabs - https://github.com/gbif/portal16/issues/306

**Comment by MortenHofft** [comment]
Hi @kbraak. Thanks. I don't agree that they are all release blockers and/or regressions. So for those we could have someone else evaluating it @ahahn-gbif and @timrobertson100 

As an example: take your release blocker " Chapter title is covered by tabs - #306 "
That an anchor scrolls 1 cm too long isn't a release blocker IMHO. The functionality wasn't there before and even if it had been I wouldn't call it a release blocker. 

So maybe it would be useful if we aligned our understanding of what a release blocker is?
