### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#721]
Translation tasks

**Notice on syntax**
Currently we do both server and client translations. It might make sense to only do client ones in the future, but then again we have server rendered pages for the sake of SEO still. But we should be careful with variables then as the two libraries have different conventions for it.

**Tasks**

*First*
* [x] **split** It seems useful to split the translation file into multiple files. Say enums, standard phrases and component/page specific files.
  * [x] make it technically possible
  * [x] split into meaningful components
* [x] **build** That requires a new build step: Translation file to be build from these sources
* [x] ~**update keys** when splitting into files it makes sense to nest enums and things differently from what we do now. So usage around the site needs to be updated to different keys.~ seems less of an issue now that they are seperated into mulitple files and folders
* [x] **integration** Test integration with Crowdin early on (github hook, pull requests, config file ... what would the flow be)
* [x] **Document integration quirks** For developers
* [ ] **Document translation flow** For translators
* [x] **contentful** translations should be picked up
* [x] **contentful vs crowdin** It should be possible to have translations of the site without having it in contentful.
* [x] **dynamic client translations** node returns the translation file to angular - it is currently hardcoded. it should return what ever is specified in the possible locales
* [x] **ng-translate** should pick up available translations
* [x] **add to interface** the interface should allow you to change versions
  * [x] initial version made avilable for reg admins to ease testing
  * [x] implement final version (translations, call for help ...?)
* [x] **language iso format** change locale format to support more than just 2 letter language iso codes as that doesn't support simplified Chinese vs traditional Chinese.
* [x] **client routes** should be updated to support non 2 letter locales
* [x] omnisearch for countries should be locale sensitive

*Secondly*
* [x] **casing** Reconsider our Casing practice. When to use lower and upper.
  * Tentative decision: phrases has capital first letter. Words is lower case, unless of course it is a word that should always be upper in that language (GBIF or Juli (in en - juli in da)
  * When doing the translations and adding more places, this wisedom of this decision is to be revisited
* [x] **remove unused** Test for unused keys to not burden translators unnecessary
* [x] **glossary** Create (or rather ask someone from the secretariat) to decide on glossary terms and description to help translators.
* [x] **remove md translations** remove the almost unused `locales/markdown` practice and move to either translation keys or Contentful.
* [x] **add locale from query params** in the node-i18n lib: Add locale from query param as an option as well, so that API calls have access to the locale as well. (in the future we might want to decouple these but at this point the node APIs sometimes return localised strings).
* [x] **remove hardcoded** Go through all the places where there is hardcoded texts and add them in the translation files instead (see https://github.com/gbif/portal16/issues/721#issuecomment-380228444)
* [x] **pluralisation** Ensure proper pluralisation - i have a feeling that we assume more than one in many places.
* [x] **try flow** Try the full translation flow in a familiar language (danish fx) - time how long time it takes so that Nodes will have an estimat of the required effort
* [x] **merge translation that exist** before doing any translation work see if any has already been done. kcopas has already done and delegated some that are located in crowdin and in spreadsheets he has locally.
* [x] **language codes in translation file** this started out with 2 letter codes only, but has since been littered with all sorts of variations. I'm not sure this is a good idea and wasn't aware it had been added. We should discuss how we believe this should be done. 
* [x] **ensure prefix on internal urls** not all internal urls currently pass on the url. They should do so. And for relative urls in contentful it should be added. Comms should be reminded to use relative urls.

*Would be nice, but isn't required to begin with*
* [ ] **RTL** Do a 'right to left' stylesheet. This should account for the fact that the content will always only be partially translated.

**Comment by kcopas** [comment]
Glossaries already exist—most current ones are in CrowdIn. Have to see about getting them out, though, I gather...

**Comment by MortenHofft** [comment]
@thomasstjerne I've added a small script to generate a copy of the english version to en-IN but with mock content.
This is to make it easier to test if everything is translated as expected. In below screenshot tabs clearly isn't for example

![screen shot 2018-04-10 at 21 58 30](https://user-images.githubusercontent.com/6759267/38580530-7ad4f3fe-3d0a-11e8-8e0f-12c17045d578.png)

To use it run `node locales/createMock` after having run `node locales/build` (that builds the english translation)
