### ISSUE TITLE
Network pages

### ISSUE THREAD

**Issue by MortenHofft** [gbif/portal16#725]
We already have network pages, but they are well hidden. We would like to give these partner networks a more prominent place and add more to the pages.

Ideas:
* [x] Create items in Contentful (similar to what we do for participants) with images, and text, links etc.
  * [x] tested in dev
  * [x] get it indexed in ES (@fmendezh is looking at this)
  * [x] reproduce in prod and clarify model with coms
* [x] update network page to use contentful item instead and seperate dataset and stats to 2 other tabs (needs to be commented in see #748
* [ ] Show the networks on datasetKey pages ~(blocked by https://github.com/gbif/registry/issues/50)~
* [x] Create a partner page (plain contenful article), with links to the partner networks
* [x] Add all the networks to contentful (https://github.com/gbif/portal16/issues/747)
* [x] add key partners to the menu?
* [ ] ~Add url aliases for key partner networks?~
* [ ] Charts
  * [x] add to interface
  * [x] API task first - requires network id to be added to occurrence index (code done, needs deployed and reindexed)
  * [ ] enable `network_key` param in routes
* [ ] maps
  * [x] add to interface
  * [x] API task first - requires maps to be created for networks (blocked by above occ index task)
  * [ ] enable `network_key` param in routes
* [ ] Add to omni search? unclear what to do as we also have OBIS as participant
* Other ?

**Comment by ahahn-gbif** [comment]
Other:
- add links to relevant publishers where applicable, e.g. OBIS tier-2 nodes like EurOBIS etc

**Comment by MortenHofft** [comment]
@ahahn-gbif
Do you mean:
1. on the network page have a list of publishers that have published dataset associated with that network
2. on a publisher page, then add a link to the network if that publisher has published at least one dataset associated with the network (so in theory there could be links to several network)

**Comment by ahahn-gbif** [comment]
@MortenHofft 
Both, ideally. 1. list the publishers together with the relevant datasets that constituted the network, 2. "published datasets contribute to the following networks" type of information on the publisher page.

**Comment by ahahn-gbif** [comment]
More "other":
- [ ] data content: network membership of datasets is maintained in the registry. Currently, there is no mechanism for publishers to link a dataset to a network, so that the table content has to be maintained at GBIFS. For all network pages that are to go live, the content of this table needs to be revised and completed

**Comment by MortenHofft** [comment]
Tagging as `blocked` as the APIs currently don't support:

*  showing network on dataset pages
* maps of network data
* search occurrences by networkKey

**Comment by dnoesgaard** [comment]
@ahahn-gbif, I looked at ways of easily listing the OBIS nodes on the network page, but with 50+ nodes I'm not sure this is feasible. Of course I can grab the list, but maintaining that would be a hassle. What do you think? 

https://www.gbif.org/network/2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6

**Comment by MattBlissett** [comment]
Maps are now produced for networks. I even added one to the debug interface: https://api.gbif.org/v2/map/debug/ol/ (look for "OBIS network" on the right, and you probably want to drag the hexagon size slider down a bit).

So, map capabilities for the OBIS network: https://api.gbif.org/v2/map/occurrence/density/capabilities.json?networkKey=2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6

Occurrences can be searched by network key: http://api.gbif.org/v1/occurrence/search?network_key=2b7c7b4f-4d4f-40d3-94de-c28b6fa054a6
